# Generated by Django 4.1.3 on 2023-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='related_user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
