# Generated by Django 4.1.3 on 2023-03-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_userprofile_related_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='related_user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
